package UTS_B.view;
import UTS_B.controller.PembayaranController;
public class FormPembayaran extends javax.swing.JFrame {
    PembayaranController controller;
    public FormPembayaran() {
        initComponents();
        controller = new PembayaranController(this);
        controller.bersihForm();
        controller.tampil();
    }
    
    public javax.swing.JTextField TxtKodePesanan () {
        return TxtKodePesanan;
    }
    
    public javax.swing.JTextField TxtNamaPemesan () {
        return TxtNamaPemesan;
    }
            
    public javax.swing.JTextField TxtTglPesan () {
        return TxtTglPesan;
    }
            
    public javax.swing.JTextField TxtHarga () {
        return TxtHarga;
    }
            
    public javax.swing.JTextField TxtOngkir () {
        return TxtOngkir;
    }
            
    public javax.swing.JTextField TxtDiskon () {
        return TxtDiskon;
    }
    
    public javax.swing.JTable TblPesan () {
        return TblPesan;
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtDiskon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtKodePesanan = new javax.swing.JTextField();
        TxtNamaPemesan = new javax.swing.JTextField();
        TxtTglPesan = new javax.swing.JTextField();
        TxtHarga = new javax.swing.JTextField();
        TxtOngkir = new javax.swing.JTextField();
        BtnInsert = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPesan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Diskon");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 210, 100, 30);

        jLabel2.setText("Kode Pesanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 100, 30);

        jLabel3.setText("Nama Pemesan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 100, 30);

        jLabel4.setText("Tgl Pesan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 90, 100, 30);
        getContentPane().add(TxtDiskon);
        TxtDiskon.setBounds(120, 210, 210, 30);

        jLabel5.setText("Harga");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 100, 30);

        jLabel6.setText("Ongkos Kirim");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 170, 100, 30);
        getContentPane().add(TxtKodePesanan);
        TxtKodePesanan.setBounds(118, 10, 210, 30);

        TxtNamaPemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaPemesanActionPerformed(evt);
            }
        });
        getContentPane().add(TxtNamaPemesan);
        TxtNamaPemesan.setBounds(120, 50, 210, 30);
        getContentPane().add(TxtTglPesan);
        TxtTglPesan.setBounds(120, 90, 210, 30);
        getContentPane().add(TxtHarga);
        TxtHarga.setBounds(120, 130, 210, 30);
        getContentPane().add(TxtOngkir);
        TxtOngkir.setBounds(120, 170, 210, 30);

        BtnInsert.setText("Insert");
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInsert);
        BtnInsert.setBounds(20, 260, 72, 23);

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUpdate);
        BtnUpdate.setBounds(130, 260, 78, 23);

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDelete);
        BtnDelete.setBounds(250, 260, 72, 23);

        TblPesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Pesanan", "Nama", "Tanggal", "Harga", "Ongkir", "Diskon", "Total"
            }
        ));
        TblPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPesanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblPesan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 292, 630, 210);

        setSize(new java.awt.Dimension(655, 543));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNamaPemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaPemesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaPemesanActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        controller.updatePembayaran();
        controller.tampil();
        controller.bersihForm();
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void TblPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPesanMouseClicked
        // TODO add your handling code here:
        controller.getPembayaran();
    }//GEN-LAST:event_TblPesanMouseClicked

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        // TODO add your handling code here:
        controller.savePembayaran();
        controller.tampil();
        controller.bersihForm();
    }//GEN-LAST:event_BtnInsertActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.tampil();
        controller.bersihForm();
    }//GEN-LAST:event_BtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTable TblPesan;
    private javax.swing.JTextField TxtDiskon;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtKodePesanan;
    private javax.swing.JTextField TxtNamaPemesan;
    private javax.swing.JTextField TxtOngkir;
    private javax.swing.JTextField TxtTglPesan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
