package alfi240523.view;

import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

public class FormPengembalian extends javax.swing.JFrame {

    public FormPengembalian() {
        initComponents();
    }

    public JComboBox<String> getCboKB() {
        return cboKB;
    }

    public void setCboKB(JComboBox<String> cboKB) {
        this.cboKB = cboKB;
    }

    public JComboBox<String> getCboNobp() {
        return cboNobp;
    }

    public void setCboNobp(JComboBox<String> cboNobp) {
        this.cboNobp = cboNobp;
    }

    public JTable getTblPengembalian() {
        return tblPengembalian;
    }

    public void setTblPengembalian(JTable tblPengembalian) {
        this.tblPengembalian = tblPengembalian;
    }

    public JTextField getTxtDenda() {
        return txtDenda;
    }

    public void setTxtDenda(JTextField txtDenda) {
        this.txtDenda = txtDenda;
    }

    public JTextField getTxtDikembalikan() {
        return txtDikembalikan;
    }

    public void setTxtDikembalikan(JTextField txtDikembalikan) {
        this.txtDikembalikan = txtDikembalikan;
    }

    public JTextField getTxtKembali() {
        return txtKembali;
    }

    public void setTxtKembali(JTextField txtKembali) {
        this.txtKembali = txtKembali;
    }

    public JTextField getTxtPinjam() {
        return txtPinjam;
    }

    public void setTxtPinjam(JTextField txtPinjam) {
        this.txtPinjam = txtPinjam;
    }

    public JTextField getTxtTerlambat() {
        return txtTerlambat;
    }

    public void setTxtTerlambat(JTextField txtTerlambat) {
        this.txtTerlambat = txtTerlambat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboKB = new javax.swing.JComboBox<>();
        cboNobp = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDenda = new javax.swing.JTextField();
        txtPinjam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKembali = new javax.swing.JTextField();
        txtDikembalikan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPengembalian = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtTerlambat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Denda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 250, 90, 30);

        jLabel2.setText("No. BP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 30);

        cboKB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboKB);
        cboKB.setBounds(130, 50, 300, 30);

        cboNobp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboNobp);
        cboNobp.setBounds(130, 10, 300, 30);

        jLabel3.setText("Kode Buku");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 90, 30);

        jLabel4.setText("Tgl. Pinjam");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 90, 90, 30);

        txtDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDendaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDenda);
        txtDenda.setBounds(130, 250, 300, 30);

        txtPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinjamActionPerformed(evt);
            }
        });
        getContentPane().add(txtPinjam);
        txtPinjam.setBounds(130, 90, 300, 30);

        jLabel5.setText("Tgl. Dikembalikan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 110, 30);

        jLabel6.setText("Terlambat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 90, 30);

        txtKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(txtKembali);
        txtKembali.setBounds(130, 130, 300, 30);

        txtDikembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDikembalikanActionPerformed(evt);
            }
        });
        getContentPane().add(txtDikembalikan);
        txtDikembalikan.setBounds(130, 170, 300, 30);

        tblPengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. BP", "Kode Buku", "Tgl. Pinjam", "Tgl. Kembali", "Tgl. Dikembalikan", "Terlambat", "Denda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPengembalian);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 290, 540, 150);

        btnExit.setText("Exit");
        getContentPane().add(btnExit);
        btnExit.setBounds(460, 220, 72, 23);

        btnInsert.setText("Insert");
        getContentPane().add(btnInsert);
        btnInsert.setBounds(460, 20, 72, 23);

        btnUpdate.setText("Update");
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(460, 70, 73, 23);

        btnDelete.setText("Delete");
        getContentPane().add(btnDelete);
        btnDelete.setBounds(460, 120, 72, 23);

        btnCancel.setText("Cancel");
        getContentPane().add(btnCancel);
        btnCancel.setBounds(460, 170, 72, 23);

        txtTerlambat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerlambatActionPerformed(evt);
            }
        });
        getContentPane().add(txtTerlambat);
        txtTerlambat.setBounds(130, 210, 300, 30);

        jLabel7.setText("Tgl. Kembali");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 130, 90, 30);

        setSize(new java.awt.Dimension(560, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDendaActionPerformed

    private void txtPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinjamActionPerformed

    private void txtKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembaliActionPerformed

    private void txtDikembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDikembalikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDikembalikanActionPerformed

    private void txtTerlambatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerlambatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerlambatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboKB;
    private javax.swing.JComboBox<String> cboNobp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tblPengembalian;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtDikembalikan;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtPinjam;
    private javax.swing.JTextField txtTerlambat;
    // End of variables declaration//GEN-END:variables
}
